sudo: required

services:
  - docker

before_install:
  - echo "Nothing to do, this is a tutorial."

script:
  - echo "Nothing to do, this is a tutorial."

after_success:
  # Build docker images
  - docker build -t mikamboo/tuto-multi-client -f ./client/Dockerfile .
  - docker build -t mikamboo/tuto-multi-nginx -f ./nginx/Dockerfile .
  - docker build -t mikamboo/tuto-multi-server -f ./server/Dockerfile .
  - docker build -t mikamboo/tuto-multi-worker -f ./worker/Dockerfile .

  # Log in to docker cli
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin

  # Push images to docker hub
  - docker push mikamboo/tuto-multi-client
  - docker push mikamboo/tuto-multi-nginx
  - docker push mikamboo/tuto-multi-server
  - docker push mikamboo/tuto-multi-worker

  # Deploy to AWS EBS
  deploy:
    provider: elasticbeanstalk
    region: eu-west-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-eu-west-1-046236623903
    bucket-path: docker-multi
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: $AWS_SECRET_KEY
    on:
      branch: master

